### ISSUE TITLE
verify cityseer implementation

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#210]
We use our own sequence of simplification functions when using cityseer. We should ensure that this sequence is as close to the implementation in the cityseer's io module as possible to avoid bias of our doing.

**Comment by jGaboardi** [comment]
Both the codebase in `cityseer` and the steps in the guide appear to have changed significantly since we created [`cityseer.ipynb`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/notebooks/methods/cityseer.ipynb), which was based on an earlier version of [the Manual Cleaning Guide](https://benchmark-urbanism.github.io/cityseer-examples/examples/graph_cleaning.html#manual-cleaning).

Now within `cityseer` there a single dedicated helper function ([`cityseer.tools.io._auto_clean_network()`](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L250)) that combines the simplification routine nicely – this is a great improvement over there. While we won't using that complete flow (e.g., plaza stuff), it is much more reliable to adjust our current sequence to match that.

The current sequence within [`cityseer.tools.io._auto_clean_network()`](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L250)) is as follows:
1. [initial deduplication](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L259C5-L260)
2. [exclusions & removal](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L261-L329)
3. [removal of dangling nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L330-L331)
4. [splitting opposing geometries](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L340)
   1. This is done with 4 sets of params
5. [consolidate nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L357) 
   1. This is done with 4 sets of params
6. [removal of degree-2 nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L367)
7. [snap gapped endings](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L369)
   1. This is entirely new, was not previously present
8. [splitting opposing geometries](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L388)
9. [removal of dangling nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L416)
10. [splitting opposing geometries](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L420)
    1. This is done [twice by default](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L492)
11. [consolidate nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L448)
    1. This is done [twice by default](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L492)
12. [removal of degree-2 nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L477)
13. [merging parallel edges](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L478)
14. [ironing out edges](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L479)
15. [removal of dangling nodes](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L481) 

The current [Manual Cleaning Guide](https://benchmark-urbanism.github.io/cityseer-examples/examples/graph_cleaning.html#manual-cleaning) mimics above with some keywords that are defaults when run from within [`cityseer.tools.io.osm_graph_from_poly()`](https://github.com/benchmark-urbanism/cityseer-api/blob/4cd1a1b582ae0d53b013e34fa59403cba71712c3/pysrc/cityseer/tools/io.py#L635).

Our current sequence in cell 3 of `cityseer.ipynb`
```python
edges = utils.read_original(city)
graph = cityseer.tools.io.nx_from_generic_geopandas(edges)
graph = cityseer.tools.graphs.nx_remove_filler_nodes(graph)
graph = cityseer.tools.graphs.nx_remove_dangling_nodes(graph)
graph = cityseer.tools.graphs.nx_split_opposing_geoms(graph)
graph = cityseer.tools.graphs.nx_remove_filler_nodes(graph)
graph = cityseer.tools.graphs.nx_consolidate_nodes(graph)
graph = cityseer.tools.graphs.nx_remove_filler_nodes(graph)
graph = cityseer.tools.graphs.nx_iron_edges(graph)
return cityseer.tools.io.geopandas_from_nx(graph, crs=edges.crs).rename_geometry(
    "geometry"
)[["geometry"]]
```

Based on the new additions to `cityseer` and the updated cleaning guide I propose we try:

```python
edges = utils.read_original(city)
graph = cityseer.tools.io.nx_from_generic_geopandas(edges)
graph = graphs.nx_deduplicate_edges(graph, dissolve_distance=20, max_ang_diff=20)
graph = graphs.nx_remove_dangling_nodes(graph, despine=0, remove_disconnected=100)
graph = graphs.nx_split_opposing_geoms(
    graph, squash_nodes=True, centroid_by_itx=True
)
graph = graphs.nx_consolidate_nodes(
    graph, crawl=False, centroid_by_itx=True
)
graph = graphs.nx_remove_filler_nodes(graph)
graph = graphs.nx_snap_gapped_endings(graph, buffer_dist=20)
graph = graphs.nx_split_opposing_geoms(
    graph,
    buffer_dist=20,
    min_node_degree=1,
    max_node_degree=1,
    squash_nodes=False,
)
graph = graphs.nx_remove_dangling_nodes(graph, despine=40)
max_angle = 120
for dist in (5, 10):
    graph = graphs.nx_split_opposing_geoms(
        graph,
        buffer_dist=dist,
        squash_nodes=True,
        centroid_by_itx=True,
        simplify_by_max_angle=max_angle,
    )
    graph = graphs.nx_consolidate_nodes(
        graph,
        buffer_dist=dist,
        crawl=True,
        centroid_by_itx=True,
        simplify_by_max_angle=max_angle,
    )
graph = graphs.nx_remove_filler_nodes(graph)
graph = graphs.nx_merge_parallel_edges(
    graph, merge_edges_by_midline=True, contains_buffer_dist=50
)
graph = graphs.nx_iron_edges(graph, min_self_loop_length=100, max_foot_tunnel_length=100)
graph = graphs.nx_remove_dangling_nodes(graph, despine=25)
return cityseer.tools.io.geopandas_from_nx(graph, crs=edges.crs).rename_geometry(
    "geometry"
)[["geometry"]]
```

I believe this follows the spirit of `cityseer`-style simplification, while introducing as little bias as possible from our end. We should not include any reliance on OSM tags or special treatment as such, to emphasize the non-use of those in `neatnet`   Thoughts?

@martinfleis @anastassiavybornova

**Comment by martinfleis** [comment]
Sounds like a plan to me! Can we document this logic of workflow retrieval also in the cityseer notebook, so it lives alongside the code?

**Comment by jGaboardi** [comment]
Also, I'll include a permalink to the `cityseer.tools.io._auto_clean_network()` function and save out a PDF of the of [the Manual Cleaning Guide](https://benchmark-urbanism.github.io/cityseer-examples/examples/graph_cleaning.html#manual-cleaning) HTML. I was trying to find a historical version of that to compare with the `4.15.2` guide, but it seems those are not curated anywhere.

**Comment by jGaboardi** [comment]
When I do this should (maybe today or this weekend) we also pin `v4.17.2`?

**Comment by anastassiavybornova** [comment]
> And should we curate this PDF within the simplification repo somewhere?
in `notebooks/methods/`? not a notebook ofc but that's where i also dumped the bash file for parenx for example

**Comment by jGaboardi** [comment]
Note:
* [`cityseer==4.17.2`](https://github.com/uscuni/simplification/blob/2210d764b9f4b5147e91aecb87b995a09dc22781/pixi.lock#L6135-L6136) is already in the `pixi.lock` ✅
